/*
 * Copyright (c) 2026
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_DMA_ALLWINNER_SUN8I_V3S_DMA_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_DMA_ALLWINNER_SUN8I_V3S_DMA_H_

#define SUN8I_V3S_DMA_DRQ_SRAM         0
#define SUN8I_V3S_DMA_DRQ_SDRAM        1
#define SUN8I_V3S_DMA_DRQ_UART0        6
#define SUN8I_V3S_DMA_DRQ_UART1        7
#define SUN8I_V3S_DMA_DRQ_UART2        8
#define SUN8I_V3S_DMA_DRQ_AUDIO_CODEC  15
#define SUN8I_V3S_DMA_DRQ_CE           16
#define SUN8I_V3S_DMA_DRQ_USB_EP1      17
#define SUN8I_V3S_DMA_DRQ_USB_EP2      18
#define SUN8I_V3S_DMA_DRQ_USB_EP3      19
#define SUN8I_V3S_DMA_DRQ_USB_EP4      20
#define SUN8I_V3S_DMA_DRQ_SPI0         23

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_DMA_ALLWINNER_SUN8I_V3S_DMA_H_ */
