/*
 * Copyright (c) 2025
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DT_BINDINGS_COUNTER_SUN8I_V3S_COUNTER_H_
#define ZEPHYR_DT_BINDINGS_COUNTER_SUN8I_V3S_COUNTER_H_

/* Timer clock source selection */
#define SUN8I_V3S_CLK_SRC_INTOSC	0
#define SUN8I_V3S_CLK_SRC_OSC24M	1

/* Timer prescaler values */
#define SUN8I_V3S_PRESCALER_DIV1		0
#define SUN8I_V3S_PRESCALER_DIV2		1
#define SUN8I_V3S_PRESCALER_DIV4		2
#define SUN8I_V3S_PRESCALER_DIV8		3
#define SUN8I_V3S_PRESCALER_DIV16		4
#define SUN8I_V3S_PRESCALER_DIV32		5
#define SUN8I_V3S_PRESCALER_DIV64		6
#define SUN8I_V3S_PRESCALER_DIV128		7

#endif /* ZEPHYR_DT_BINDINGS_COUNTER_SUN8I_V3S_COUNTER_H_ */
